#!/usr/bin/env python3
"""Apply a bounded root-XY lock only for visually planted GMR slide episodes.

The input evidence must be generated by ``audit_video_foot_contact_evidence``.
Only a foot that is both visually planted relative to the background and
geometrically near the GMR floor may request a root correction.  Episodes that
need a large correction or disagree during double support are recorded and the
candidate remains rejected rather than being silently distorted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pickle
from pathlib import Path
from typing import Any

import mujoco
import numpy as np


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _runs(mask: np.ndarray, minimum: int) -> list[np.ndarray]:
    result: list[np.ndarray] = []
    start: int | None = None
    for index, enabled in enumerate(mask.tolist() + [False]):
        if enabled and start is None:
            start = index
        elif not enabled and start is not None:
            if index - start >= minimum:
                result.append(np.arange(start, index, dtype=np.int64))
            start = None
    return result


def _foot_meshes(model: mujoco.MjModel, body_name: str) -> tuple[int, list[tuple[int, np.ndarray]]]:
    body = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name)
    if body < 0:
        raise ValueError(f"missing body {body_name}")
    meshes: list[tuple[int, np.ndarray]] = []
    for geom in range(model.ngeom):
        if int(model.geom_bodyid[geom]) != body or int(model.geom_type[geom]) != int(mujoco.mjtGeom.mjGEOM_MESH):
            continue
        if int(model.geom_group[geom]) != 1:
            continue
        mesh = int(model.geom_dataid[geom])
        start = int(model.mesh_vertadr[mesh])
        count = int(model.mesh_vertnum[mesh])
        meshes.append((geom, model.mesh_vert[start : start + count].copy()))
    if not meshes:
        raise ValueError(f"no visible mesh for {body_name}")
    return body, meshes


def _states(motion: dict[str, Any], robot_xml: Path) -> tuple[np.ndarray, np.ndarray]:
    root = np.asarray(motion["root_pos"], dtype=np.float64)
    rotation = np.asarray(motion["root_rot"], dtype=np.float64)
    dof = np.asarray(motion["dof_pos"], dtype=np.float64)
    model = mujoco.MjModel.from_xml_path(str(robot_xml))
    if model.nq - 7 != dof.shape[1]:
        raise ValueError("robot XML and motion DoF counts differ")
    feet = {
        "left": _foot_meshes(model, "left_ankle_roll_link"),
        "right": _foot_meshes(model, "right_ankle_roll_link"),
    }
    xy = np.zeros((len(root), 2, 2), dtype=np.float64)
    height = np.zeros((len(root), 2), dtype=np.float64)
    data = mujoco.MjData(model)
    for frame in range(len(root)):
        data.qpos[:3] = root[frame]
        data.qpos[3:7] = rotation[frame][[3, 0, 1, 2]]
        data.qpos[7:] = dof[frame]
        mujoco.mj_forward(model, data)
        for side_index, side in enumerate(("left", "right")):
            body, meshes = feet[side]
            xy[frame, side_index] = data.xpos[body, :2]
            low = float("inf")
            for geom, vertices in meshes:
                matrix = data.geom_xmat[geom].reshape(3, 3)
                low = min(low, float(np.min((vertices @ matrix.T + data.geom_xpos[geom])[:, 2])))
            height[frame, side_index] = low
    return xy, height


def _summary(values: np.ndarray) -> dict[str, float]:
    lengths = np.linalg.norm(values, axis=1)
    return {
        "maximum_m": float(np.max(lengths, initial=0.0)),
        "p95_m": float(np.percentile(lengths, 95)) if len(lengths) else 0.0,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-motion", required=True, type=Path)
    parser.add_argument("--robot-xml", required=True, type=Path)
    parser.add_argument("--evidence", required=True, type=Path)
    parser.add_argument("--output-motion", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    parser.add_argument("--speed-tolerance-m-s", type=float, default=0.25)
    parser.add_argument("--contact-height-m", type=float, default=0.015)
    parser.add_argument("--minimum-episode-frames", type=int, default=5)
    parser.add_argument("--max-root-correction-m", type=float, default=0.08)
    parser.add_argument("--max-root-correction-p95-m", type=float, default=0.05)
    parser.add_argument("--max-double-support-conflict-m", type=float, default=0.03)
    parser.add_argument("--max-root-step-m", type=float, default=0.025)
    parser.add_argument("--fade-frames", type=int, default=2)
    args = parser.parse_args()
    if min(args.speed_tolerance_m_s, args.contact_height_m, args.max_root_correction_m, args.max_root_step_m) <= 0.0:
        raise ValueError("positive contact and correction thresholds are required")
    with args.input_motion.open("rb") as stream:
        motion = pickle.load(stream)
    if not isinstance(motion, dict):
        raise ValueError("motion is not a dictionary")
    root = np.asarray(motion["root_pos"], dtype=np.float64)
    frames = len(root)
    fps = float(motion.get("fps", 30.0))
    xy, height = _states(motion, args.robot_xml)
    speed = np.zeros((frames, 2), dtype=np.float64)
    if frames > 1:
        speed[1:] = np.linalg.norm(np.diff(xy, axis=0), axis=2) * fps
        speed[:-1] = np.maximum(speed[:-1], speed[1:])
    with np.load(args.evidence, allow_pickle=False) as evidence:
        phases = {
            "left": np.asarray(evidence["left_phase"], dtype=np.int8),
            "right": np.asarray(evidence["right_phase"], dtype=np.int8),
        }
    if any(value.shape != (frames,) for value in phases.values()):
        raise ValueError("evidence and robot motion have different frame counts")

    desired = np.full((frames, 2, 2), np.nan, dtype=np.float64)
    episode_reports: list[dict[str, Any]] = []
    for side_index, side in enumerate(("left", "right")):
        visual_planted = phases[side] == 1
        near = (height[:, side_index] >= -0.005) & (height[:, side_index] <= args.contact_height_m)
        mask = visual_planted & near & (speed[:, side_index] > args.speed_tolerance_m_s)
        for episode in _runs(mask, args.minimum_episode_frames):
            first = int(episode[0])
            reference = first
            for candidate in range(first - 1, -1, -1):
                if visual_planted[candidate] and near[candidate] and speed[candidate, side_index] <= args.speed_tolerance_m_s:
                    reference = candidate
                    break
            anchor = xy[reference, side_index].copy()
            requested = anchor[None] - xy[episode, side_index]
            desired[episode, side_index] = requested
            episode_reports.append({
                "side": side,
                "frame_range": [int(episode[0]), int(episode[-1])],
                "frame_count": int(len(episode)),
                "anchor_frame": reference,
                "requested_root_xy_correction": _summary(requested),
            })

    correction = np.zeros((frames, 2), dtype=np.float64)
    conflicts: list[dict[str, Any]] = []
    for frame in range(frames):
        left = desired[frame, 0]
        right = desired[frame, 1]
        has_left = np.all(np.isfinite(left))
        has_right = np.all(np.isfinite(right))
        if has_left and has_right:
            conflict = float(np.linalg.norm(left - right))
            if conflict > args.max_double_support_conflict_m:
                conflicts.append({"frame": frame, "magnitude_m": conflict})
                continue
            correction[frame] = 0.5 * (left + right)
        elif has_left:
            correction[frame] = left
        elif has_right:
            correction[frame] = right

    # Fade each isolated episode into the unmodified trajectory.  This does
    # not alter an evidence-backed contact frame outside the requested range.
    active = np.any(np.isfinite(desired), axis=(1, 2))
    for run in _runs(active, 1):
        first, last = int(run[0]), int(run[-1])
        for offset in range(1, args.fade_frames + 1):
            before = first - offset
            after = last + offset
            weight = (args.fade_frames - offset + 1) / (args.fade_frames + 1)
            if before >= 0:
                correction[before] = correction[first] * weight
            if after < frames:
                correction[after] = correction[last] * weight
    step = np.linalg.norm(np.diff(correction, axis=0), axis=1) if frames > 1 else np.empty(0)
    correction_stats = _summary(correction)
    failures: list[str] = []
    if correction_stats["maximum_m"] > args.max_root_correction_m:
        failures.append("root_xy_correction_exceeds_maximum")
    if correction_stats["p95_m"] > args.max_root_correction_p95_m:
        failures.append("root_xy_correction_exceeds_p95_limit")
    if len(step) and float(np.max(step)) > args.max_root_step_m:
        failures.append("root_xy_step_exceeds_limit")
    if conflicts:
        failures.append("double_support_contact_lock_conflict")
    if not episode_reports:
        failures.append("no_visual_planted_sliding_episode")

    result = dict(motion)
    root_out = root.copy()
    root_out[:, :2] += correction
    result["root_pos"] = root_out.astype(np.asarray(motion["root_pos"]).dtype, copy=False)
    result["two_d_contact_root_lock"] = {
        "kind": "background_compensated_visual_planted_root_xy_lock",
        "input_sha256": _sha256(args.input_motion),
        "evidence_sha256": _sha256(args.evidence),
        "weights_modified": False,
        "root_rotation_unchanged": True,
        "dof_unchanged": True,
    }
    args.output_motion.parent.mkdir(parents=True, exist_ok=True)
    with args.output_motion.open("wb") as stream:
        pickle.dump(result, stream)
    report = {
        "schema_version": 1,
        "kind": "background_compensated_visual_planted_root_xy_lock",
        "input_motion": str(args.input_motion),
        "input_sha256": _sha256(args.input_motion),
        "evidence": str(args.evidence),
        "evidence_sha256": _sha256(args.evidence),
        "output_motion": str(args.output_motion),
        "output_sha256": _sha256(args.output_motion),
        "weights_modified": False,
        "root_rotation_unchanged": bool(np.array_equal(result["root_rot"], motion["root_rot"])),
        "dof_unchanged": bool(np.array_equal(result["dof_pos"], motion["dof_pos"])),
        "correction": correction_stats,
        "max_root_step_m": float(np.max(step)) if len(step) else 0.0,
        "episodes": episode_reports,
        "double_support_conflicts": conflicts,
        "failures": failures,
        "accepted": not failures,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "accepted": report["accepted"],
        "episodes": len(episode_reports),
        "correction": correction_stats,
        "max_root_step_m": report["max_root_step_m"],
        "failures": failures,
    }))


if __name__ == "__main__":
    main()
