#!/usr/bin/env bash
# One coordinated hand-constraint profile for source MANO and target robot IK.
#
# responsive:   clear, fast gestures; least damping
# balanced:     default for normal 30 FPS videos
# conservative: noisy/distant/occluded hands; strongest repair and damping

GVHMR_HAND_CONSTRAINT_PROFILE="${GVHMR_HAND_CONSTRAINT_PROFILE:-balanced}"

case "$GVHMR_HAND_CONSTRAINT_PROFILE" in
    responsive)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-15}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-5}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-9}"
        GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.15}"
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.65}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.28}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.050}"
        GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED="${GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED:-1}"
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.015}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-3}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.16}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.14}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-3}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-3}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.16}"
        ;;
    balanced)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-30}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-10}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-15}"
        if [ "${GVHMR_HAND_BACKEND:-}" = "wilor" ]; then
            GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.25}"
        else
            GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.30}"
        fi
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.85}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.22}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.035}"
        GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED="${GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED:-1}"
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.03}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-5}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.12}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.10}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-5}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-3}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.12}"
        ;;
    conservative)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-45}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-15}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-21}"
        GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.40}"
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.95}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.18}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.028}"
        GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED="${GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED:-0}"
        # The final Sharpa IK is the last stage before rendering.  Tighten it
        # modestly for noisy hand observations without re-filtering the body.
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.08}"
        GMR_SHARPA_LOW_CONF_TEMPORAL_GAIN="${GMR_SHARPA_LOW_CONF_TEMPORAL_GAIN:-4.0}"
        GMR_SHARPA_RELIABILITY_SMOOTH_WINDOW="${GMR_SHARPA_RELIABILITY_SMOOTH_WINDOW:-11}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-9}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.075}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.055}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-9}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-5}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.09}"
        ;;
    *)
        echo "Unsupported GVHMR_HAND_CONSTRAINT_PROFILE=$GVHMR_HAND_CONSTRAINT_PROFILE" >&2
        echo "Use responsive|balanced|conservative" >&2
        return 2 2>/dev/null || exit 2
        ;;
esac

# Visible-hand refinement runs after the first temporal pass. Re-filter that
# final MANO track once so the GVHMR render and the Sharpa sidecar share the
# same temporally stable fingers.
GVHMR_HAND_REFINE_MODE="${GVHMR_HAND_REFINE_MODE:-raw}"
GVHMR_FINAL_FINGER_SMOOTH_AFTER_VISIBLE_REFINE="${GVHMR_FINAL_FINGER_SMOOTH_AFTER_VISIBLE_REFINE:-1}"
GVHMR_FINAL_FINGER_SMOOTH_WINDOW="${GVHMR_FINAL_FINGER_SMOOTH_WINDOW:-9}"
GVHMR_FINAL_FINGER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINAL_FINGER_RELIABLE_SMOOTH_WEIGHT:-0.20}"
GVHMR_FINAL_FINGER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINAL_FINGER_WEAK_SMOOTH_WEIGHT:-0.60}"
GVHMR_FINAL_FINGER_BAD_SMOOTH_WEIGHT="${GVHMR_FINAL_FINGER_BAD_SMOOTH_WEIGHT:-0.85}"

export GVHMR_HAND_CONSTRAINT_PROFILE
export GVHMR_FILTER_MANO_WRIST GVHMR_FILTER_MANO_TEMPORAL GVHMR_FILTER_MANO_FINGERS
export GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD
export GVHMR_FINGER_FILTER_SMOOTH_WINDOW
export GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT
export GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA GVHMR_FINGER_FILTER_OPEN_RESCUE_ENABLED
export GVHMR_HAND_REFINE_MODE
export GVHMR_FINAL_FINGER_SMOOTH_AFTER_VISIBLE_REFINE
export GVHMR_FINAL_FINGER_SMOOTH_WINDOW
export GVHMR_FINAL_FINGER_RELIABLE_SMOOTH_WEIGHT GVHMR_FINAL_FINGER_WEAK_SMOOTH_WEIGHT GVHMR_FINAL_FINGER_BAD_SMOOTH_WEIGHT
export GMR_SHARPA_TEMPORAL_COST GMR_SHARPA_LOW_CONF_TEMPORAL_GAIN
export GMR_SHARPA_RELIABILITY_SMOOTH_WINDOW GMR_SHARPA_SMOOTH_WINDOW
export GMR_SHARPA_MAX_DELTA GMR_SHARPA_MAX_ACCEL
export GMR_HAND_SMOOTH_WINDOW GMR_HAND_MEDIAN_WINDOW GMR_HAND_MAX_DELTA
