#!/usr/bin/env bash
# One coordinated hand-constraint profile for source MANO and target robot IK.
#
# responsive:   clear, fast gestures; least damping
# balanced:     default for normal 30 FPS videos
# conservative: noisy/distant/occluded hands; strongest repair and damping

GVHMR_HAND_CONSTRAINT_PROFILE="${GVHMR_HAND_CONSTRAINT_PROFILE:-balanced}"

case "$GVHMR_HAND_CONSTRAINT_PROFILE" in
    responsive)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-15}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-5}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-9}"
        GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.15}"
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.65}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.28}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.050}"
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.015}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-3}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.16}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.14}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-3}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-3}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.16}"
        ;;
    balanced)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-30}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-10}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-15}"
        if [ "${GVHMR_HAND_BACKEND:-}" = "wilor" ]; then
            GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.25}"
        else
            GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.30}"
        fi
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.85}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.22}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.035}"
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.03}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-5}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.12}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.10}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-5}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-3}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.12}"
        ;;
    conservative)
        GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
        GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-1}"
        GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-1}"
        GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-45}"
        GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-15}"
        GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-21}"
        GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.40}"
        GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.95}"
        GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.18}"
        GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.028}"
        GMR_SHARPA_TEMPORAL_COST="${GMR_SHARPA_TEMPORAL_COST:-0.06}"
        GMR_SHARPA_SMOOTH_WINDOW="${GMR_SHARPA_SMOOTH_WINDOW:-7}"
        GMR_SHARPA_MAX_DELTA="${GMR_SHARPA_MAX_DELTA:-0.09}"
        GMR_SHARPA_MAX_ACCEL="${GMR_SHARPA_MAX_ACCEL:-0.07}"
        GMR_HAND_SMOOTH_WINDOW="${GMR_HAND_SMOOTH_WINDOW:-9}"
        GMR_HAND_MEDIAN_WINDOW="${GMR_HAND_MEDIAN_WINDOW:-5}"
        GMR_HAND_MAX_DELTA="${GMR_HAND_MAX_DELTA:-0.09}"
        ;;
    *)
        echo "Unsupported GVHMR_HAND_CONSTRAINT_PROFILE=$GVHMR_HAND_CONSTRAINT_PROFILE" >&2
        echo "Use responsive|balanced|conservative" >&2
        return 2 2>/dev/null || exit 2
        ;;
esac

# The filtered MANO track is already the track rendered by GVHMR. A second
# clean/interpolation pass would create a different gesture for GMR.
GVHMR_HAND_REFINE_MODE="${GVHMR_HAND_REFINE_MODE:-raw}"

export GVHMR_HAND_CONSTRAINT_PROFILE
export GVHMR_FILTER_MANO_WRIST GVHMR_FILTER_MANO_TEMPORAL GVHMR_FILTER_MANO_FINGERS
export GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD
export GVHMR_FINGER_FILTER_SMOOTH_WINDOW
export GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT
export GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA
export GVHMR_HAND_REFINE_MODE
export GMR_SHARPA_TEMPORAL_COST GMR_SHARPA_SMOOTH_WINDOW
export GMR_SHARPA_MAX_DELTA GMR_SHARPA_MAX_ACCEL
export GMR_HAND_SMOOTH_WINDOW GMR_HAND_MEDIAN_WINDOW GMR_HAND_MAX_DELTA
