#!/bin/bash
# ============================================================================
# Batch pipeline: dataset_new6 videos -> GVHMR-hand -> Locomotion -> PHC -> GMR
# ============================================================================
# Usage:
#   cd <repo-root>
#   bash GVHMR-hand/GVHMR-main/tools/pipeline/run_batch_dataset6.sh
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GVHMR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PIPELINE_ROOT="${PIPELINE_ROOT:-$(cd "${GVHMR}/../.." && pwd)}"

DATASET="${DATASET:-${PIPELINE_ROOT}/dataset_new6}"
CLIP_FILTER="${CLIP_FILTER:-}"
PIPELINE_SCRIPT="${SCRIPT_DIR}/run_pipeline.sh"
OUTPUT_BASE="${OUTPUT_BASE:-${PIPELINE_ROOT}/output_dir/kungfu_hand}"
USE_WORK_VIDEO="${USE_WORK_VIDEO:-1}"
WORK_DATASET="${WORK_DATASET:-${PIPELINE_ROOT}/dataset_new6_work_1280}"
WORK_WIDTH="${WORK_WIDTH:-1280}"
WORK_HEIGHT="${WORK_HEIGHT:-960}"
WORK_CRF="${WORK_CRF:-18}"
FORCE_WORK_VIDEO="${FORCE_WORK_VIDEO:-0}"
GVHMR_BATCH_SIZE="${GVHMR_BATCH_SIZE:-1}"
GVHMR_HAMER_BATCH_SIZE="${GVHMR_HAMER_BATCH_SIZE:-2}"
GVHMR_FORCE_HAND_PREPROCESS="${GVHMR_FORCE_HAND_PREPROCESS:-0}"
GVHMR_ISOLATE_HAND_PREPROCESS="${GVHMR_ISOLATE_HAND_PREPROCESS:-auto}"
GVHMR_HAND_BACKEND="${GVHMR_HAND_BACKEND:-hamer}"
GVHMR_HAND_CONSTRAINT_PROFILE="${GVHMR_HAND_CONSTRAINT_PROFILE:-balanced}"
GVHMR_WILOR_ROOT="${GVHMR_WILOR_ROOT:-${GVHMR}/third-party/WiLoR}"
GVHMR_WILOR_CHECKPOINT="${GVHMR_WILOR_CHECKPOINT:-${GVHMR_WILOR_ROOT}/pretrained_models/wilor_final.ckpt}"
GVHMR_WILOR_CONFIG="${GVHMR_WILOR_CONFIG:-${GVHMR_WILOR_ROOT}/pretrained_models/model_config.yaml}"
GVHMR_WILOR_FAST="${GVHMR_WILOR_FAST:-0}"
GVHMR_HAND4WHOLEPP_ROOT="${GVHMR_HAND4WHOLEPP_ROOT:-${GVHMR}/third-party/Hand4Whole-plus-plus_RELEASE}"
GVHMR_HAND4WHOLEPP_SNAPSHOT="${GVHMR_HAND4WHOLEPP_SNAPSHOT:-${GVHMR_HAND4WHOLEPP_ROOT}/demo/snapshot_6.pth}"
GVHMR_HAND4WHOLEPP_PYTHON="${GVHMR_HAND4WHOLEPP_PYTHON:-}"
GVHMR_HAND4WHOLEPP_BATCH_SIZE="${GVHMR_HAND4WHOLEPP_BATCH_SIZE:-4}"
GVHMR_HAND4WHOLEPP_YOLO_MODEL="${GVHMR_HAND4WHOLEPP_YOLO_MODEL:-yolo11n.pt}"
GVHMR_HAND4WHOLEPP_JOINT_SOURCE="${GVHMR_HAND4WHOLEPP_JOINT_SOURCE:-direct_mano}"
GVHMR_VITPOSE_IMG_DS="${GVHMR_VITPOSE_IMG_DS:-1.0}"
GVHMR_HAND_KPT_CONF_THR="${GVHMR_HAND_KPT_CONF_THR:-0.35}"
GVHMR_HAND_KPT_LOW_CONF_THR="${GVHMR_HAND_KPT_LOW_CONF_THR:-0.2}"
GVHMR_HAND_KPT_HI_MIN_KEYPOINTS="${GVHMR_HAND_KPT_HI_MIN_KEYPOINTS:-6}"
GVHMR_HAND_MIN_KEYPOINTS="${GVHMR_HAND_MIN_KEYPOINTS:-3}"
GVHMR_HAMER_BBOX_RESCALE="${GVHMR_HAMER_BBOX_RESCALE:-2.6}"
GVHMR_HAMER_BBOX_RESCALE_CANDIDATES="${GVHMR_HAMER_BBOX_RESCALE_CANDIDATES:-3.0,3.5,4.0}"
GVHMR_HAMER_CANDIDATE_SWITCH_PENALTY="${GVHMR_HAMER_CANDIDATE_SWITCH_PENALTY:-8.0}"
GVHMR_HAND_BBOX_MIN_SIZE="${GVHMR_HAND_BBOX_MIN_SIZE:-96}"
GVHMR_HAND_BBOX_SMOOTHING="${GVHMR_HAND_BBOX_SMOOTHING:-0.55}"
GVHMR_HAND_BBOX_MAX_JUMP="${GVHMR_HAND_BBOX_MAX_JUMP:-90}"
GVHMR_HAND_BBOX_OVERLAP_IOU="${GVHMR_HAND_BBOX_OVERLAP_IOU:-0.55}"
GVHMR_HAND_BBOX_COLLISION_SCORE_RATIO="${GVHMR_HAND_BBOX_COLLISION_SCORE_RATIO:-1.35}"
GVHMR_HAMER_REFINE_STEPS="${GVHMR_HAMER_REFINE_STEPS:-8}"
GVHMR_HAMER_REFINE_LR="${GVHMR_HAMER_REFINE_LR:-0.03}"
GVHMR_HAMER_REFINE_CONF_THR="${GVHMR_HAMER_REFINE_CONF_THR:-0.45}"
GVHMR_HAMER_REFINE_MIN_KEYPOINTS="${GVHMR_HAMER_REFINE_MIN_KEYPOINTS:-6}"
GVHMR_HAMER_REFINE_POSE_PRIOR="${GVHMR_HAMER_REFINE_POSE_PRIOR:-0.005}"
GVHMR_HAMER_REFINE_GLOBAL_PRIOR="${GVHMR_HAMER_REFINE_GLOBAL_PRIOR:-0.01}"
GVHMR_FILTER_MANO_WRIST="${GVHMR_FILTER_MANO_WRIST:-0}"
GVHMR_WRIST_FILTER_W_TEMP="${GVHMR_WRIST_FILTER_W_TEMP:-2.0}"
GVHMR_WRIST_FILTER_W_BODY="${GVHMR_WRIST_FILTER_W_BODY:-0.5}"
GVHMR_WRIST_FILTER_W_TEMP_LOW_CONF="${GVHMR_WRIST_FILTER_W_TEMP_LOW_CONF:-4.0}"
GVHMR_WRIST_FILTER_W_BODY_LOW_CONF="${GVHMR_WRIST_FILTER_W_BODY_LOW_CONF:-1.0}"
GVHMR_WRIST_FILTER_MIX_WEIGHT="${GVHMR_WRIST_FILTER_MIX_WEIGHT:-0.35}"
GVHMR_WRIST_FILTER_HAMER_PENALTY="${GVHMR_WRIST_FILTER_HAMER_PENALTY:-0.0}"
GVHMR_WRIST_FILTER_FLIP_PENALTY="${GVHMR_WRIST_FILTER_FLIP_PENALTY:-0.15}"
GVHMR_WRIST_FILTER_BODY_PENALTY="${GVHMR_WRIST_FILTER_BODY_PENALTY:-0.35}"
GVHMR_WRIST_FILTER_MIX_PENALTY="${GVHMR_WRIST_FILTER_MIX_PENALTY:-0.1}"
GVHMR_WRIST_FILTER_INVALID_HAMER_PENALTY="${GVHMR_WRIST_FILTER_INVALID_HAMER_PENALTY:-1.0}"
GVHMR_WRIST_FILTER_INVALID_FLIP_PENALTY="${GVHMR_WRIST_FILTER_INVALID_FLIP_PENALTY:-1.0}"
GVHMR_WRIST_FILTER_INVALID_MIX_PENALTY="${GVHMR_WRIST_FILTER_INVALID_MIX_PENALTY:-0.2}"
GVHMR_FILTER_MANO_TEMPORAL="${GVHMR_FILTER_MANO_TEMPORAL:-0}"
GVHMR_TEMPORAL_FILTER_REPROJ_ERROR_THR="${GVHMR_TEMPORAL_FILTER_REPROJ_ERROR_THR:-75}"
GVHMR_TEMPORAL_FILTER_BBOX_WINDOW="${GVHMR_TEMPORAL_FILTER_BBOX_WINDOW:-30}"
GVHMR_TEMPORAL_FILTER_BBOX_SHRINK_RATIO="${GVHMR_TEMPORAL_FILTER_BBOX_SHRINK_RATIO:-0.65}"
GVHMR_TEMPORAL_FILTER_MIN_BBOX_FOREARM_RATIO="${GVHMR_TEMPORAL_FILTER_MIN_BBOX_FOREARM_RATIO:-0.45}"
GVHMR_TEMPORAL_FILTER_BBOX_JUMP_RATIO="${GVHMR_TEMPORAL_FILTER_BBOX_JUMP_RATIO:-1.75}"
GVHMR_TEMPORAL_FILTER_BBOX_OVERLAP_IOU="${GVHMR_TEMPORAL_FILTER_BBOX_OVERLAP_IOU:-0.55}"
GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_RATIO="${GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_RATIO:-0.75}"
GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_MIN_FOREARM_RATIO="${GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_MIN_FOREARM_RATIO:-0.45}"
GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP:-60}"
GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="${GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD:-15}"
GVHMR_FILTER_MANO_FINGERS="${GVHMR_FILTER_MANO_FINGERS:-0}"
GVHMR_FINGER_FILTER_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_SMOOTH_WINDOW:-17}"
GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT:-0.22}"
GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT:-0.90}"
GVHMR_FINGER_FILTER_BAD_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_BAD_SMOOTH_WEIGHT:-1.0}"
GVHMR_FINGER_FILTER_MAX_INTERP_GAP="${GVHMR_FINGER_FILTER_MAX_INTERP_GAP:-120}"
GVHMR_FINGER_FILTER_MAX_EDGE_HOLD="${GVHMR_FINGER_FILTER_MAX_EDGE_HOLD:-90}"
GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA:-0.25}"
GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="${GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA:-0.04}"
GVHMR_FINGER_FILTER_WRIST_SMOOTH_WINDOW="${GVHMR_FINGER_FILTER_WRIST_SMOOTH_WINDOW:-11}"
GVHMR_FINGER_FILTER_WRIST_RELIABLE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WRIST_RELIABLE_SMOOTH_WEIGHT:-0.25}"
GVHMR_FINGER_FILTER_WRIST_WEAK_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WRIST_WEAK_SMOOTH_WEIGHT:-0.80}"
GVHMR_FINGER_FILTER_WRIST_BAD_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_WRIST_BAD_SMOOTH_WEIGHT:-1.0}"
GVHMR_FINGER_FILTER_MAX_WRIST_ANGLE_DELTA="${GVHMR_FINGER_FILTER_MAX_WRIST_ANGLE_DELTA:-0.25}"
GVHMR_FINGER_FILTER_HAND_SIZE_FLOOR_RATIO="${GVHMR_FINGER_FILTER_HAND_SIZE_FLOOR_RATIO:-0.96}"
GVHMR_FINGER_FILTER_OPEN_RESCUE_WEIGHT="${GVHMR_FINGER_FILTER_OPEN_RESCUE_WEIGHT:-0.30}"
GVHMR_FINGER_FILTER_OPEN_RESCUE_SMOOTH_WEIGHT="${GVHMR_FINGER_FILTER_OPEN_RESCUE_SMOOTH_WEIGHT:-0.70}"
GVHMR_DIAGNOSE_HAND="${GVHMR_DIAGNOSE_HAND:-0}"
GVHMR_DIAGNOSE_HAND_WIDTH="${GVHMR_DIAGNOSE_HAND_WIDTH:-960}"
GVHMR_SKIP_RENDER="${GVHMR_SKIP_RENDER:-0}"
GVHMR_LOW_MEMORY="${GVHMR_LOW_MEMORY:-1}"
SKIP_PHC="${SKIP_PHC:-0}"
FORCE_PHC="${FORCE_PHC:-0}"
GVHMR_HAND_REFINE_MODE="${GVHMR_HAND_REFINE_MODE:-clean}"
GVHMR_HAND_REPROJ_ERROR_THR="${GVHMR_HAND_REPROJ_ERROR_THR:-75}"
GVHMR_HAND_REPROJ_ERROR_RATIO_THR="${GVHMR_HAND_REPROJ_ERROR_RATIO_THR:-0.45}"
GVHMR_HAND_WRIST_OFFSET_MODE="${GVHMR_HAND_WRIST_OFFSET_MODE:-auto}"
GVHMR_HAND_WRIST_OFFSET_SMOOTH_WINDOW="${GVHMR_HAND_WRIST_OFFSET_SMOOTH_WINDOW:-15}"
GVHMR_HAND_SPIKE_MAD_MULTIPLIER="${GVHMR_HAND_SPIKE_MAD_MULTIPLIER:-8}"
GVHMR_HAND_SPIKE_ABS_THRESHOLD="${GVHMR_HAND_SPIKE_ABS_THRESHOLD:-1.2}"
GVHMR_HAND_REFINE_GAP_MERGE="${GVHMR_HAND_REFINE_GAP_MERGE:-2}"
GVHMR_HAND_REFINE_MAX_BURST="${GVHMR_HAND_REFINE_MAX_BURST:-10}"
GVHMR_HAND_REFINE_SMOOTH_WINDOW="${GVHMR_HAND_REFINE_SMOOTH_WINDOW:-0}"
RENDER_COMPARISON="${RENDER_COMPARISON:-0}"

RUN_GMR="${RUN_GMR:-1}"

# Batch-specific defaults must be set before sourcing the shared defaults.
# Otherwise pipeline_defaults.sh initializes these to 0/hold and the later
# "${VAR:-...}" expressions cannot override those non-empty values.
GMR_AUTO_HAND_NPZ="${GMR_AUTO_HAND_NPZ:-1}"
GMR_HAND_INVALID_MODE="${GMR_HAND_INVALID_MODE:-interp}"

# Source shared GMR defaults while preserving the batch-specific values above.
source "${PIPELINE_ROOT}/GMR-master/pipeline_defaults.sh"

# --- batch-specific GMR overrides ---
GMR_SCRIPT="${GMR_SCRIPT:-${PIPELINE_ROOT}/GMR-master/run_show_gmr_batch.sh}"
GMR_OUT_ROOT="${GMR_OUT_ROOT:-$OUTPUT_BASE}"

G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[0;34m'; N='\033[0m'

echo "============================================================"
echo "  Batch pipeline: dataset_new6 -> GVHMR-hand -> GMR"
echo "============================================================"
echo "Dataset: $DATASET"
if [ -n "$CLIP_FILTER" ]; then
    echo "Clip filter: $CLIP_FILTER"
fi
echo "Output:  $OUTPUT_BASE"
echo "Script:  $PIPELINE_SCRIPT"
echo "GMR:     $RUN_GMR ($GMR_EMBODIMENT_LABEL; body_asset=$GMR_ROBOT)"
echo "Work:    ${WORK_WIDTH}x${WORK_HEIGHT}, hand_backend=${GVHMR_HAND_BACKEND}, h4w_joint_source=${GVHMR_HAND4WHOLEPP_JOINT_SOURCE}, isolate_hand=${GVHMR_ISOLATE_HAND_PREPROCESS}, low_memory=${GVHMR_LOW_MEMORY}, vitpose_img_ds=${GVHMR_VITPOSE_IMG_DS}, hand_crop_scales=${GVHMR_HAMER_BBOX_RESCALE_CANDIDATES:-$GVHMR_HAMER_BBOX_RESCALE}, switch_penalty=${GVHMR_HAMER_CANDIDATE_SWITCH_PENALTY}, hand_conf=${GVHMR_HAND_KPT_CONF_THR}/${GVHMR_HAND_KPT_LOW_CONF_THR}, bbox_smooth=${GVHMR_HAND_BBOX_SMOOTHING}, bbox_jump=${GVHMR_HAND_BBOX_MAX_JUMP}, bbox_iou=${GVHMR_HAND_BBOX_OVERLAP_IOU}, bbox_ratio=${GVHMR_HAND_BBOX_COLLISION_SCORE_RATIO}, refine_steps=${GVHMR_HAMER_REFINE_STEPS}"
echo "Wrist:   filter=${GVHMR_FILTER_MANO_WRIST}, w_temp=${GVHMR_WRIST_FILTER_W_TEMP}, w_body=${GVHMR_WRIST_FILTER_W_BODY}"
echo "Temporal filter: ${GVHMR_FILTER_MANO_TEMPORAL}, window=${GVHMR_TEMPORAL_FILTER_BBOX_WINDOW}, max_gap=${GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP}"
echo "Finger filter: ${GVHMR_FILTER_MANO_FINGERS}, window=${GVHMR_FINGER_FILTER_SMOOTH_WINDOW}, max_gap=${GVHMR_FINGER_FILTER_MAX_INTERP_GAP}, size_floor=${GVHMR_FINGER_FILTER_HAND_SIZE_FLOOR_RATIO}"
echo "Constraint profile: ${GVHMR_HAND_CONSTRAINT_PROFILE}"
echo "Hand diagnostic: ${GVHMR_DIAGNOSE_HAND}, width=${GVHMR_DIAGNOSE_HAND_WIDTH}"
echo "Palm:    source=${GMR_PALM_ROLL_SOURCE}, gain=${GMR_PALM_ROLL_GAIN}, max_delta=${GMR_PALM_ROLL_MAX_DELTA}, max_abs=${GMR_PALM_ROLL_MAX_ABS}, branch=${GMR_PALM_ROLL_BRANCH_MODE}"
echo "GMR hand: selection=${GMR_HAND_MODEL}, mode=${GMR_HAND_RETARGET_MODE}, sharpa=${GMR_SHARPA_HANDS}, brainco=${GMR_BRAINCO_HANDS}"
echo ""
mkdir -p "$OUTPUT_BASE"

mapfile -t VIDEOS < <(
    find "$DATASET" -maxdepth 1 -type f \
        \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.avi' -o -iname '*.mkv' -o -iname '*.m4v' \) \
        -print0 | sort -z | xargs -0 -n1 echo
)
if [ -n "$CLIP_FILTER" ]; then
    FILTERED_VIDEOS=()
    for video in "${VIDEOS[@]}"; do
        if [[ "$(basename "$video")" == *"$CLIP_FILTER"* ]]; then
            FILTERED_VIDEOS+=("$video")
        fi
    done
    VIDEOS=("${FILTERED_VIDEOS[@]}")
fi
TOTAL=${#VIDEOS[@]}

if [ "$TOTAL" -eq 0 ]; then
    echo -e "${R}No video files found in $DATASET${N}"
    exit 1
fi

echo "Found $TOTAL videos:"
for video in "${VIDEOS[@]}"; do
    echo "  $(basename "$video")"
done
echo ""

PASS=0
FAIL=0
FAIL_LIST=()
PASS_LIST=()
for i in "${!VIDEOS[@]}"; do
    VIDEO="${VIDEOS[$i]}"
    NAME="$(basename "$VIDEO")"
    NAME="${NAME%.*}"
    NUM=$((i + 1))
    CLIP_LOG="${OUTPUT_BASE}/${NAME}.pipeline.log"

    echo ""
    echo -e "${B}------------------------------------------------------------${N}"
    echo -e "${B}[$NUM/$TOTAL] $NAME${N}"
    echo -e "${B}------------------------------------------------------------${N}"

    INPUT_VIDEO="$VIDEO"
    if [ "$USE_WORK_VIDEO" = "1" ]; then
        mkdir -p "$WORK_DATASET"
        INPUT_VIDEO="${WORK_DATASET}/${NAME}.mp4"
        WORK_CONFIG_MARKER="${INPUT_VIDEO}.config"
        WORK_CONFIG="$(
            printf '%s\n' \
                "source=$(realpath "$VIDEO")" \
                "source_stat=$(stat -c '%s:%Y' "$VIDEO")" \
                "width=$WORK_WIDTH" \
                "height=$WORK_HEIGHT" \
                "crf=$WORK_CRF"
        )"
        WORK_CONFIG_MATCH=0
        if [ -f "$WORK_CONFIG_MARKER" ] && [ "$(cat "$WORK_CONFIG_MARKER")" = "$WORK_CONFIG" ]; then
            WORK_CONFIG_MATCH=1
        fi
        if [ "$FORCE_WORK_VIDEO" = "1" ] || [ ! -f "$INPUT_VIDEO" ] || [ "$WORK_CONFIG_MATCH" != "1" ]; then
            echo -e "${B}Creating work video:${N} $INPUT_VIDEO"
            ffmpeg -hide_banner -loglevel error -y \
                -i "$VIDEO" \
                -vf "scale=${WORK_WIDTH}:${WORK_HEIGHT}:force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2" \
                -c:v libx264 -preset veryfast -crf "$WORK_CRF" -pix_fmt yuv420p -an \
                "$INPUT_VIDEO"
            printf '%s\n' "$WORK_CONFIG" > "$WORK_CONFIG_MARKER"
        fi
    fi

    if GVHMR_BATCH_SIZE="$GVHMR_BATCH_SIZE" \
       GVHMR_HAMER_BATCH_SIZE="$GVHMR_HAMER_BATCH_SIZE" \
	       GVHMR_FORCE_HAND_PREPROCESS="$GVHMR_FORCE_HAND_PREPROCESS" \
	       GVHMR_ISOLATE_HAND_PREPROCESS="$GVHMR_ISOLATE_HAND_PREPROCESS" \
       GVHMR_HAND_BACKEND="$GVHMR_HAND_BACKEND" \
       GVHMR_WILOR_ROOT="$GVHMR_WILOR_ROOT" \
       GVHMR_WILOR_CHECKPOINT="$GVHMR_WILOR_CHECKPOINT" \
       GVHMR_WILOR_CONFIG="$GVHMR_WILOR_CONFIG" \
       GVHMR_WILOR_FAST="$GVHMR_WILOR_FAST" \
       GVHMR_HAND4WHOLEPP_ROOT="$GVHMR_HAND4WHOLEPP_ROOT" \
       GVHMR_HAND4WHOLEPP_SNAPSHOT="$GVHMR_HAND4WHOLEPP_SNAPSHOT" \
       GVHMR_HAND4WHOLEPP_PYTHON="$GVHMR_HAND4WHOLEPP_PYTHON" \
	       GVHMR_HAND4WHOLEPP_BATCH_SIZE="$GVHMR_HAND4WHOLEPP_BATCH_SIZE" \
	       GVHMR_HAND4WHOLEPP_YOLO_MODEL="$GVHMR_HAND4WHOLEPP_YOLO_MODEL" \
	       GVHMR_HAND4WHOLEPP_JOINT_SOURCE="$GVHMR_HAND4WHOLEPP_JOINT_SOURCE" \
       GVHMR_LOW_MEMORY="$GVHMR_LOW_MEMORY" \
       GVHMR_VITPOSE_IMG_DS="$GVHMR_VITPOSE_IMG_DS" \
       GVHMR_HAND_KPT_CONF_THR="$GVHMR_HAND_KPT_CONF_THR" \
       GVHMR_HAND_KPT_LOW_CONF_THR="$GVHMR_HAND_KPT_LOW_CONF_THR" \
       GVHMR_HAND_KPT_HI_MIN_KEYPOINTS="$GVHMR_HAND_KPT_HI_MIN_KEYPOINTS" \
       GVHMR_HAND_MIN_KEYPOINTS="$GVHMR_HAND_MIN_KEYPOINTS" \
       GVHMR_HAMER_BBOX_RESCALE="$GVHMR_HAMER_BBOX_RESCALE" \
       GVHMR_HAMER_BBOX_RESCALE_CANDIDATES="$GVHMR_HAMER_BBOX_RESCALE_CANDIDATES" \
       GVHMR_HAMER_CANDIDATE_SWITCH_PENALTY="$GVHMR_HAMER_CANDIDATE_SWITCH_PENALTY" \
       GVHMR_HAND_BBOX_MIN_SIZE="$GVHMR_HAND_BBOX_MIN_SIZE" \
       GVHMR_HAND_BBOX_SMOOTHING="$GVHMR_HAND_BBOX_SMOOTHING" \
       GVHMR_HAND_BBOX_MAX_JUMP="$GVHMR_HAND_BBOX_MAX_JUMP" \
       GVHMR_HAND_BBOX_OVERLAP_IOU="$GVHMR_HAND_BBOX_OVERLAP_IOU" \
       GVHMR_HAND_BBOX_COLLISION_SCORE_RATIO="$GVHMR_HAND_BBOX_COLLISION_SCORE_RATIO" \
       GVHMR_HAMER_REFINE_STEPS="$GVHMR_HAMER_REFINE_STEPS" \
       GVHMR_HAMER_REFINE_LR="$GVHMR_HAMER_REFINE_LR" \
	       GVHMR_HAMER_REFINE_CONF_THR="$GVHMR_HAMER_REFINE_CONF_THR" \
	       GVHMR_HAMER_REFINE_MIN_KEYPOINTS="$GVHMR_HAMER_REFINE_MIN_KEYPOINTS" \
	       GVHMR_HAMER_REFINE_POSE_PRIOR="$GVHMR_HAMER_REFINE_POSE_PRIOR" \
	       GVHMR_HAMER_REFINE_GLOBAL_PRIOR="$GVHMR_HAMER_REFINE_GLOBAL_PRIOR" \
	       GVHMR_FILTER_MANO_WRIST="$GVHMR_FILTER_MANO_WRIST" \
	       GVHMR_WRIST_FILTER_W_TEMP="$GVHMR_WRIST_FILTER_W_TEMP" \
	       GVHMR_WRIST_FILTER_W_BODY="$GVHMR_WRIST_FILTER_W_BODY" \
	       GVHMR_WRIST_FILTER_W_TEMP_LOW_CONF="$GVHMR_WRIST_FILTER_W_TEMP_LOW_CONF" \
	       GVHMR_WRIST_FILTER_W_BODY_LOW_CONF="$GVHMR_WRIST_FILTER_W_BODY_LOW_CONF" \
	       GVHMR_WRIST_FILTER_MIX_WEIGHT="$GVHMR_WRIST_FILTER_MIX_WEIGHT" \
	       GVHMR_WRIST_FILTER_HAMER_PENALTY="$GVHMR_WRIST_FILTER_HAMER_PENALTY" \
	       GVHMR_WRIST_FILTER_FLIP_PENALTY="$GVHMR_WRIST_FILTER_FLIP_PENALTY" \
	       GVHMR_WRIST_FILTER_BODY_PENALTY="$GVHMR_WRIST_FILTER_BODY_PENALTY" \
	       GVHMR_WRIST_FILTER_MIX_PENALTY="$GVHMR_WRIST_FILTER_MIX_PENALTY" \
		       GVHMR_WRIST_FILTER_INVALID_HAMER_PENALTY="$GVHMR_WRIST_FILTER_INVALID_HAMER_PENALTY" \
		       GVHMR_WRIST_FILTER_INVALID_FLIP_PENALTY="$GVHMR_WRIST_FILTER_INVALID_FLIP_PENALTY" \
		       GVHMR_WRIST_FILTER_INVALID_MIX_PENALTY="$GVHMR_WRIST_FILTER_INVALID_MIX_PENALTY" \
		       GVHMR_FILTER_MANO_TEMPORAL="$GVHMR_FILTER_MANO_TEMPORAL" \
		       GVHMR_HAND_CONSTRAINT_PROFILE="$GVHMR_HAND_CONSTRAINT_PROFILE" \
		       GVHMR_TEMPORAL_FILTER_REPROJ_ERROR_THR="$GVHMR_TEMPORAL_FILTER_REPROJ_ERROR_THR" \
		       GVHMR_TEMPORAL_FILTER_BBOX_WINDOW="$GVHMR_TEMPORAL_FILTER_BBOX_WINDOW" \
		       GVHMR_TEMPORAL_FILTER_BBOX_SHRINK_RATIO="$GVHMR_TEMPORAL_FILTER_BBOX_SHRINK_RATIO" \
		       GVHMR_TEMPORAL_FILTER_MIN_BBOX_FOREARM_RATIO="$GVHMR_TEMPORAL_FILTER_MIN_BBOX_FOREARM_RATIO" \
		       GVHMR_TEMPORAL_FILTER_BBOX_JUMP_RATIO="$GVHMR_TEMPORAL_FILTER_BBOX_JUMP_RATIO" \
		       GVHMR_TEMPORAL_FILTER_BBOX_OVERLAP_IOU="$GVHMR_TEMPORAL_FILTER_BBOX_OVERLAP_IOU" \
		       GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_RATIO="$GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_RATIO" \
		       GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_MIN_FOREARM_RATIO="$GVHMR_TEMPORAL_FILTER_BBOX_SIZE_FLOOR_MIN_FOREARM_RATIO" \
		       GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP="$GVHMR_TEMPORAL_FILTER_MAX_INTERP_GAP" \
		       GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD="$GVHMR_TEMPORAL_FILTER_MAX_EDGE_HOLD" \
		       GVHMR_FILTER_MANO_FINGERS="$GVHMR_FILTER_MANO_FINGERS" \
		       GVHMR_FINGER_FILTER_SMOOTH_WINDOW="$GVHMR_FINGER_FILTER_SMOOTH_WINDOW" \
		       GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_RELIABLE_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_WEAK_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_BAD_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_BAD_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_MAX_INTERP_GAP="$GVHMR_FINGER_FILTER_MAX_INTERP_GAP" \
		       GVHMR_FINGER_FILTER_MAX_EDGE_HOLD="$GVHMR_FINGER_FILTER_MAX_EDGE_HOLD" \
		       GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA="$GVHMR_FINGER_FILTER_MAX_JOINT_ANGLE_DELTA" \
		       GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA="$GVHMR_FINGER_FILTER_MAX_JOINT_XYZ_DELTA" \
		       GVHMR_FINGER_FILTER_WRIST_SMOOTH_WINDOW="$GVHMR_FINGER_FILTER_WRIST_SMOOTH_WINDOW" \
		       GVHMR_FINGER_FILTER_WRIST_RELIABLE_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_WRIST_RELIABLE_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_WRIST_WEAK_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_WRIST_WEAK_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_WRIST_BAD_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_WRIST_BAD_SMOOTH_WEIGHT" \
		       GVHMR_FINGER_FILTER_MAX_WRIST_ANGLE_DELTA="$GVHMR_FINGER_FILTER_MAX_WRIST_ANGLE_DELTA" \
		       GVHMR_FINGER_FILTER_HAND_SIZE_FLOOR_RATIO="$GVHMR_FINGER_FILTER_HAND_SIZE_FLOOR_RATIO" \
		       GVHMR_FINGER_FILTER_OPEN_RESCUE_WEIGHT="$GVHMR_FINGER_FILTER_OPEN_RESCUE_WEIGHT" \
		       GVHMR_FINGER_FILTER_OPEN_RESCUE_SMOOTH_WEIGHT="$GVHMR_FINGER_FILTER_OPEN_RESCUE_SMOOTH_WEIGHT" \
		       GVHMR_DIAGNOSE_HAND="$GVHMR_DIAGNOSE_HAND" \
		       GVHMR_DIAGNOSE_HAND_WIDTH="$GVHMR_DIAGNOSE_HAND_WIDTH" \
		       GVHMR_SKIP_RENDER="$GVHMR_SKIP_RENDER" \
	       GVHMR_HAND_REFINE_MODE="$GVHMR_HAND_REFINE_MODE" \
	       GVHMR_HAND_REPROJ_ERROR_THR="$GVHMR_HAND_REPROJ_ERROR_THR" \
	       GVHMR_HAND_REPROJ_ERROR_RATIO_THR="$GVHMR_HAND_REPROJ_ERROR_RATIO_THR" \
	       GVHMR_HAND_WRIST_OFFSET_MODE="$GVHMR_HAND_WRIST_OFFSET_MODE" \
	       GVHMR_HAND_WRIST_OFFSET_SMOOTH_WINDOW="$GVHMR_HAND_WRIST_OFFSET_SMOOTH_WINDOW" \
	       GVHMR_HAND_SPIKE_MAD_MULTIPLIER="$GVHMR_HAND_SPIKE_MAD_MULTIPLIER" \
	       GVHMR_HAND_SPIKE_ABS_THRESHOLD="$GVHMR_HAND_SPIKE_ABS_THRESHOLD" \
	       GVHMR_HAND_REFINE_GAP_MERGE="$GVHMR_HAND_REFINE_GAP_MERGE" \
	       GVHMR_HAND_REFINE_MAX_BURST="$GVHMR_HAND_REFINE_MAX_BURST" \
	       GVHMR_HAND_REFINE_SMOOTH_WINDOW="$GVHMR_HAND_REFINE_SMOOTH_WINDOW" \
	       SKIP_PHC="$SKIP_PHC" \
	       FORCE_PHC="$FORCE_PHC" \
	       RENDER_COMPARISON="$RENDER_COMPARISON" \
	       bash "$PIPELINE_SCRIPT" "$INPUT_VIDEO" "${OUTPUT_BASE}/${NAME}" 2>&1 | tee "$CLIP_LOG"; then
        echo -e "${G}[$NUM/$TOTAL] PASS: $NAME${N}"
        PASS=$((PASS + 1))
        PASS_LIST+=("$NAME")
    else
        echo -e "${R}[$NUM/$TOTAL] FAIL: $NAME${N}"
        FAIL=$((FAIL + 1))
        FAIL_LIST+=("$NAME")
    fi
done

echo ""
echo "============================================================"
echo "  Batch complete: $PASS passed / $FAIL failed / $TOTAL total"
echo "============================================================"
if [ "$FAIL" -gt 0 ]; then
    echo -e "${Y}Failed clips:${N}"
    for name in "${FAIL_LIST[@]}"; do
        echo "  $name"
    done
fi
echo "Output directory: $OUTPUT_BASE"

if [ "$RUN_GMR" = "1" ] && [ "$PASS" -gt 0 ]; then
    PASS_CSV=""
    for name in "${PASS_LIST[@]}"; do
        PASS_CSV="${PASS_CSV:+$PASS_CSV,}$name"
    done
    RUN_GMR_INCLUDE_CLIPS="${GMR_INCLUDE_CLIPS:-$PASS_CSV}"
    echo ""
    echo "============================================================"
    echo "  GMR batch: $GMR_EMBODIMENT_LABEL"
    echo "============================================================"
    SHOW_ROOT="$OUTPUT_BASE" \
    OUT_ROOT="$GMR_OUT_ROOT" \
    GMR_SOURCE="$GMR_SOURCE" \
    GMR_ROBOT="$GMR_ROBOT" \
    GMR_INCLUDE_CLIPS="$RUN_GMR_INCLUDE_CLIPS" \
    GMR_MODEL_TYPE="$GMR_MODEL_TYPE" \
    GMR_AUTO_HAND_NPZ="$GMR_AUTO_HAND_NPZ" \
    GMR_RENDER="$GMR_RENDER" \
    GMR_COMPOSITE="$GMR_COMPOSITE" \
    GMR_HAND_INVALID_MODE="$GMR_HAND_INVALID_MODE" \
    GMR_HAND_INTERP_MAX_GAP="$GMR_HAND_INTERP_MAX_GAP" \
    GMR_HAND_RETARGET_MODE="$GMR_HAND_RETARGET_MODE" \
    GMR_HAND_ANGLE_SCALE="$GMR_HAND_ANGLE_SCALE" \
    GMR_HAND_CURL_POWER="$GMR_HAND_CURL_POWER" \
    GMR_HAND_WRIST_ORIENTATION_MODE="$GMR_HAND_WRIST_ORIENTATION_MODE" \
    GMR_PALM_ROLL_MODE="$GMR_PALM_ROLL_MODE" \
    GMR_PALM_ROLL_GAIN="$GMR_PALM_ROLL_GAIN" \
    GMR_PALM_ROLL_SOURCE="$GMR_PALM_ROLL_SOURCE" \
    GMR_PALM_ROLL_NORMAL_DOT_MIN="$GMR_PALM_ROLL_NORMAL_DOT_MIN" \
    GMR_LEFT_PALM_ROLL_SIGN="$GMR_LEFT_PALM_ROLL_SIGN" \
    GMR_RIGHT_PALM_ROLL_SIGN="$GMR_RIGHT_PALM_ROLL_SIGN" \
    GMR_PALM_ROLL_SMOOTH_WINDOW="$GMR_PALM_ROLL_SMOOTH_WINDOW" \
    GMR_PALM_ROLL_MAX_DELTA="$GMR_PALM_ROLL_MAX_DELTA" \
    GMR_PALM_ROLL_MAX_ABS="$GMR_PALM_ROLL_MAX_ABS" \
    GMR_PALM_ROLL_BRANCH_MODE="$GMR_PALM_ROLL_BRANCH_MODE" \
    GMR_PALM_ROLL_BRANCH_CANDIDATES="$GMR_PALM_ROLL_BRANCH_CANDIDATES" \
    GMR_PALM_ROLL_BRANCH_ANCHOR_FRAMES="$GMR_PALM_ROLL_BRANCH_ANCHOR_FRAMES" \
    GMR_PALM_ROLL_BRANCH_TRANSITION_WEIGHT="$GMR_PALM_ROLL_BRANCH_TRANSITION_WEIGHT" \
    GMR_PALM_ROLL_BRANCH_PENALTY="$GMR_PALM_ROLL_BRANCH_PENALTY" \
    GMR_PALM_ROLL_BRANCH_ANCHOR_PENALTY="$GMR_PALM_ROLL_BRANCH_ANCHOR_PENALTY" \
    GMR_PALM_ROLL_BRANCH_RANGE_PENALTY="$GMR_PALM_ROLL_BRANCH_RANGE_PENALTY" \
    GMR_WRIST_PITCH_YAW_STABILIZE="$GMR_WRIST_PITCH_YAW_STABILIZE" \
    GMR_SHARPA_HANDS="$GMR_SHARPA_HANDS" \
    GMR_SHARPA_AUTO_RETARGET="$GMR_SHARPA_AUTO_RETARGET" \
    GMR_SHARPA_HAND_NPZ_NAME="$GMR_SHARPA_HAND_NPZ_NAME" \
    GMR_SHARPA_MOUNT_POS="$GMR_SHARPA_MOUNT_POS" \
    GMR_SHARPA_MOUNT_QUAT="$GMR_SHARPA_MOUNT_QUAT" \
    GMR_SHARPA_LEFT_MOUNT_QUAT="$GMR_SHARPA_LEFT_MOUNT_QUAT" \
    GMR_SHARPA_RIGHT_MOUNT_QUAT="$GMR_SHARPA_RIGHT_MOUNT_QUAT" \
    GMR_SHARPA_SCALE="$GMR_SHARPA_SCALE" \
    GMR_SHARPA_STEPS="$GMR_SHARPA_STEPS" \
    GMR_SHARPA_INIT_STEPS="$GMR_SHARPA_INIT_STEPS" \
    GMR_SHARPA_WRIST_POS_COST="$GMR_SHARPA_WRIST_POS_COST" \
    GMR_SHARPA_WRIST_ORI_COST="$GMR_SHARPA_WRIST_ORI_COST" \
    GMR_SHARPA_FINGER_POS_COST="$GMR_SHARPA_FINGER_POS_COST" \
    GMR_SHARPA_JOINT_POS_COST="$GMR_SHARPA_JOINT_POS_COST" \
    GMR_SHARPA_POSTURE_COST="$GMR_SHARPA_POSTURE_COST" \
    GMR_SHARPA_TEMPORAL_COST="$GMR_SHARPA_TEMPORAL_COST" \
    GMR_SHARPA_LOW_CONF_TEMPORAL_GAIN="$GMR_SHARPA_LOW_CONF_TEMPORAL_GAIN" \
    GMR_SHARPA_MIN_TARGET_CONFIDENCE_SCALE="$GMR_SHARPA_MIN_TARGET_CONFIDENCE_SCALE" \
    GMR_SHARPA_SMOOTH_WINDOW="$GMR_SHARPA_SMOOTH_WINDOW" \
    GMR_SHARPA_MAX_DELTA="$GMR_SHARPA_MAX_DELTA" \
    GMR_SHARPA_MAX_ACCEL="$GMR_SHARPA_MAX_ACCEL" \
    GMR_SHARPA_LOW_CONF_ACCEL_SCALE="$GMR_SHARPA_LOW_CONF_ACCEL_SCALE" \
    GMR_SHARPA_REPROJ_GOOD_PX="$GMR_SHARPA_REPROJ_GOOD_PX" \
    GMR_SHARPA_REPROJ_BAD_PX="$GMR_SHARPA_REPROJ_BAD_PX" \
    GMR_SHARPA_REPROJ_GOOD_RATIO="$GMR_SHARPA_REPROJ_GOOD_RATIO" \
    GMR_SHARPA_REPROJ_BAD_RATIO="$GMR_SHARPA_REPROJ_BAD_RATIO" \
    GMR_SHARPA_MAX_PIP_BEND_DEG="$GMR_SHARPA_MAX_PIP_BEND_DEG" \
    GMR_SHARPA_MAX_DIP_BEND_DEG="$GMR_SHARPA_MAX_DIP_BEND_DEG" \
    GMR_SHARPA_MAX_SOURCE_BONE_DELTA_DEG="$GMR_SHARPA_MAX_SOURCE_BONE_DELTA_DEG" \
    GMR_SHARPA_MAX_SOURCE_BONE_LENGTH_RATIO="$GMR_SHARPA_MAX_SOURCE_BONE_LENGTH_RATIO" \
    GMR_SHARPA_ANATOMIC_REPAIR_MAX_GAP="$GMR_SHARPA_ANATOMIC_REPAIR_MAX_GAP" \
    GMR_HAND_MODEL="$GMR_HAND_MODEL" \
    GMR_BRAINCO_HANDS="$GMR_BRAINCO_HANDS" \
    GMR_BRAINCO_AUTO_RETARGET="$GMR_BRAINCO_AUTO_RETARGET" \
    GMR_BRAINCO_HAND_NPZ_NAME="$GMR_BRAINCO_HAND_NPZ_NAME" \
    GMR_BRAINCO_ROOT="$GMR_BRAINCO_ROOT" \
    GMR_BRAINCO_LEFT_MOUNT_POS="$GMR_BRAINCO_LEFT_MOUNT_POS" \
    GMR_BRAINCO_RIGHT_MOUNT_POS="$GMR_BRAINCO_RIGHT_MOUNT_POS" \
    GMR_BRAINCO_LEFT_MOUNT_QUAT="$GMR_BRAINCO_LEFT_MOUNT_QUAT" \
    GMR_BRAINCO_RIGHT_MOUNT_QUAT="$GMR_BRAINCO_RIGHT_MOUNT_QUAT" \
    GMR_CAMERA_SOURCE="$GMR_CAMERA_SOURCE" \
    GMR_MUJOCO_GL="$GMR_MUJOCO_GL" \
    GMR_COMPOSITE_PANEL_HEIGHT="$GMR_COMPOSITE_PANEL_HEIGHT" \
    bash "$GMR_SCRIPT"
    echo ""
    echo "All outputs under: $OUTPUT_BASE"
    echo "  2x2 composite:   <clip>/composite_2x2.mp4"
    echo "  GMR robot PKL:   <clip>/robot_motion.pkl"
    echo "  GMR render:      <clip>/${GMR_RENDER_NAME}"
fi

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
