#!/usr/bin/env python3
"""Recompute wrist-local MANO joints after a pose-changing hand filter.

Hand4Whole++ writes direct-MANO finger rotations and a 21-joint track derived
from the same MANO geometry.  Temporal filters may edit rotations, so copying
or independently interpolating the old joints breaks that contract.  This tool
uses the saved per-frame MANO betas and the same 21-point regressor to restore
the geometry from the final pose.

It is intentionally strict: no zero-beta fallback is allowed.  Historical
outputs without ``*_hand_betas`` must be regenerated by Hand4Whole++ first.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch
from scipy.spatial.transform import Rotation


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mano_params", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--hand4wholepp_root", required=True, type=Path)
    parser.add_argument("--summary", type=Path, default=None)
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument(
        "--verify_input",
        action="store_true",
        help=(
            "Require the incoming joints to already match the reconstructed "
            "direct-MANO geometry. Use only on a fresh, unfiltered adapter output."
        ),
    )
    parser.add_argument(
        "--verify_p95_max_mm",
        type=float,
        default=0.50,
        help="Maximum accepted p95 raw-adapter residual during --verify_input.",
    )
    parser.add_argument(
        "--verify_max_mm",
        type=float,
        default=1.00,
        help="Maximum accepted absolute raw-adapter residual during --verify_input.",
    )
    return parser.parse_args()


def _as_numpy(value: Any, key: str) -> np.ndarray:
    if torch.is_tensor(value):
        value = value.detach().cpu().numpy()
    array = np.asarray(value)
    if not np.isfinite(array).all():
        raise ValueError(f"{key} contains NaN or infinity")
    return array


def _to_like(array: np.ndarray, template: Any) -> Any:
    if torch.is_tensor(template):
        return torch.as_tensor(array, dtype=template.dtype, device=template.device)
    return np.asarray(array, dtype=np.asarray(template).dtype)


def _matrix_or_axis_angle(
    value: Any,
    key: str,
    prefix_shape: tuple[int, ...],
) -> np.ndarray:
    array = _as_numpy(value, key).astype(np.float64, copy=False)
    if array.shape == prefix_shape + (3,):
        return array.astype(np.float32, copy=False)
    if array.shape == prefix_shape + (3, 3):
        return Rotation.from_matrix(array.reshape(-1, 3, 3)).as_rotvec().reshape(
            prefix_shape + (3,)
        ).astype(np.float32)
    raise ValueError(
        f"{key} must have shape {prefix_shape + (3,)} or "
        f"{prefix_shape + (3, 3)}, got {array.shape}"
    )


def _betas(value: Any, side: str, people: int, frames: int) -> np.ndarray:
    array = _as_numpy(value, f"{side}_hand_betas").astype(np.float32, copy=False)
    if array.shape == (people, frames, 10):
        return array
    if array.shape == (people, 10):
        return np.broadcast_to(array[:, None, :], (people, frames, 10)).copy()
    raise ValueError(
        f"{side}_hand_betas must have shape {(people, frames, 10)} or "
        f"{(people, 10)}, got {array.shape}"
    )


def _stats_mm(delta_m: np.ndarray) -> dict[str, float]:
    finite = np.asarray(delta_m, dtype=np.float64)
    finite = finite[np.isfinite(finite)] * 1000.0
    if not finite.size:
        return {"mean": float("nan"), "p95": float("nan"), "max": float("nan")}
    return {
        "mean": float(np.mean(finite)),
        "p95": float(np.percentile(finite, 95)),
        "max": float(np.max(finite)),
    }


def _load_mano_layers(root: Path) -> tuple[Any, np.ndarray]:
    root = root.expanduser().resolve()
    main_dir = root / "main"
    demo_dir = root / "demo"
    if not main_dir.is_dir() or not demo_dir.is_dir():
        raise FileNotFoundError(f"invalid Hand4Whole++ root: {root}")
    original_cwd = Path.cwd()
    sys.path.insert(0, str(main_dir))
    try:
        os.chdir(demo_dir)
        from config import cfg  # noqa: F401
        from utils.mano import mano
    finally:
        os.chdir(original_cwd)
    regressor = np.asarray(mano.kpt["regressor"], dtype=np.float32)
    if regressor.shape != (21, 778):
        raise ValueError(f"unexpected MANO joint regressor shape: {regressor.shape}")
    return mano, regressor


def _recompute_side(
    data: dict[str, Any],
    side: str,
    mano: Any,
    regressor: np.ndarray,
    batch_size: int,
) -> tuple[np.ndarray, dict[str, Any]]:
    pose_key = f"{side}_hand_pose"
    global_key = f"{side}_hand_global_orient"
    beta_key = f"{side}_hand_betas"
    joints_key = f"{side}_hand_joints_3d"
    for key in (pose_key, global_key, beta_key, joints_key):
        if key not in data:
            raise KeyError(f"required direct-MANO field missing: {key}")

    pose_array = _as_numpy(data[pose_key], pose_key)
    if pose_array.ndim not in {3, 4, 5}:
        raise ValueError(f"unexpected {pose_key} shape: {pose_array.shape}")
    if pose_array.ndim == 3 and pose_array.shape[-1] == 45:
        pose_array = pose_array[None]
    elif pose_array.ndim == 4 and pose_array.shape[-2:] == (15, 3):
        pose_array = pose_array[None]
    elif pose_array.ndim == 4 and pose_array.shape[-3:] == (15, 3, 3):
        pose_array = pose_array[None]
    if pose_array.ndim not in {4, 5}:
        raise ValueError(f"unexpected normalized {pose_key} shape: {pose_array.shape}")
    people, frames = pose_array.shape[:2]
    if pose_array.shape[-1] == 45:
        pose_axis = pose_array.reshape(people, frames, 15, 3)
    elif pose_array.shape[-2:] == (15, 3):
        pose_axis = pose_array
    elif pose_array.shape[-3:] == (15, 3, 3):
        pose_axis = _matrix_or_axis_angle(
            pose_array, pose_key, (people, frames, 15)
        )
    else:
        raise ValueError(f"unexpected {pose_key} shape: {pose_array.shape}")
    global_axis = _matrix_or_axis_angle(
        data[global_key], global_key, (people, frames)
    )
    beta_array = _betas(data[beta_key], side, people, frames)

    total = people * frames
    joints = np.empty((total, 21, 3), dtype=np.float32)
    regressor_tensor = torch.from_numpy(regressor)
    layer = mano.layer[side].cpu().eval()
    for start in range(0, total, batch_size):
        end = min(total, start + batch_size)
        global_batch = torch.from_numpy(global_axis.reshape(total, 3)[start:end])
        pose_batch = torch.from_numpy(pose_axis.reshape(total, 45)[start:end])
        beta_batch = torch.from_numpy(beta_array.reshape(total, 10)[start:end])
        with torch.no_grad():
            vertices = layer(
                global_orient=global_batch,
                hand_pose=pose_batch,
                betas=beta_batch,
            ).vertices
            batch_joints = torch.einsum("jv,nvc->njc", regressor_tensor, vertices)
            batch_joints = batch_joints - batch_joints[:, :1, :]
        joints[start:end] = batch_joints.cpu().numpy().astype(np.float32)

    joints = joints.reshape(people, frames, 21, 3)
    original = _as_numpy(data[joints_key], joints_key)
    if original.shape == (frames, 21, 3) and people == 1:
        original = original[None]
    if original.shape != joints.shape:
        raise ValueError(
            f"{joints_key} shape {original.shape} does not match {joints.shape}"
        )
    delta = np.linalg.norm(joints - original, axis=-1)
    return joints, {
        "frames": int(total),
        "pre_recompute_delta_mm": _stats_mm(delta),
    }


def main() -> None:
    args = parse_args()
    if args.batch_size < 1:
        raise ValueError("--batch_size must be positive")
    if args.verify_p95_max_mm < 0 or args.verify_max_mm < 0:
        raise ValueError("verification residual limits must be non-negative")
    source = args.mano_params.expanduser().resolve()
    output = args.output.expanduser().resolve()
    if not source.is_file():
        raise FileNotFoundError(source)
    data = torch.load(source, map_location="cpu", weights_only=False)
    if not isinstance(data, dict):
        raise TypeError("mano_params must contain a dictionary")
    mano, regressor = _load_mano_layers(args.hand4wholepp_root)
    result = dict(data)
    summary: dict[str, Any] = {
        "schema_version": 1,
        "input": str(source),
        "output": str(output),
        "method": "direct_mano_forward_recompute",
        "batch_size": int(args.batch_size),
        "verify_input": bool(args.verify_input),
        "verify_p95_max_mm": float(args.verify_p95_max_mm),
        "verify_max_mm": float(args.verify_max_mm),
        "regressor_sha256": hashlib.sha256(regressor.tobytes()).hexdigest(),
        "sides": {},
    }
    for side in ("left", "right"):
        joints_key = f"{side}_hand_joints_3d"
        recomputed, side_summary = _recompute_side(
            data, side, mano, regressor, args.batch_size
        )
        stats = side_summary["pre_recompute_delta_mm"]
        if args.verify_input and (
            stats["p95"] > args.verify_p95_max_mm
            or stats["max"] > args.verify_max_mm
        ):
            raise RuntimeError(
                f"{side} raw direct-MANO verification failed: "
                f"p95={stats['p95']:.4f}mm max={stats['max']:.4f}mm "
                f"> p95_limit={args.verify_p95_max_mm:.4f}mm "
                f"or max_limit={args.verify_max_mm:.4f}mm"
            )
        result.setdefault(f"{side}_hand_joints_3d_pre_recompute", data[joints_key])
        result[joints_key] = _to_like(recomputed, data[joints_key])
        result[f"{side}_hand_joints_3d_recomputed_mask"] = _to_like(
            np.ones(recomputed.shape[:2], dtype=bool),
            data.get(f"{side}_hand_valid", data[joints_key]),
        )
        summary["sides"][side] = side_summary
    result["mano_joint_recompute_config"] = summary.copy()
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.tmp")
    try:
        torch.save(result, temporary)
        os.replace(temporary, output)
    finally:
        if temporary.exists():
            temporary.unlink()
    summary_path = args.summary.expanduser().resolve() if args.summary else output.with_suffix(".json")
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"Saved recomputed direct-MANO joints: {output}")
    for side, values in summary["sides"].items():
        stats = values["pre_recompute_delta_mm"]
        print(
            f"  {side}: input_delta_mm mean={stats['mean']:.4f} "
            f"p95={stats['p95']:.4f} max={stats['max']:.4f}"
        )


if __name__ == "__main__":
    main()
